ConsultoriaBalofi/ConsultoriaBalofi/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'', include('registration.urls')),
	url(r'', include('balofi.urls')),
]

ConsultoriaBalofi/balofi/urls.py
from django.conf.urls import include,url
from . import views
from django.contrib import admin

urlpatterns = [
    url(r'^home$', views.Home, name='Home'),
	url(r'^cliente/(.+)$', views.editar, name='cliente'),
	url(r'^consulta/(.+)$', views.consultar, name='consulta'),
	url(r'^registro$', views.registrar, name='registro'),
	url(r'^productos/(.+)$', views.VerProductos, name='productos'),
	url(r'^editarProducto/(?P<pk>.+)/(?P<rfc>.+)$', views.editar_Producto, name='editarProducto'),
	url(r'^consultaProducto/(?P<pk>.+)/(?P<rfc>.+)$', views.consultar_Producto, name='consultaProducto'),
	url(r'^registroProducto/(.+)$', views.registrar_Producto, name='registroProducto'),
	url(r'^facturas/(.+)$', views.VerFacturas, name='facturas'),
	url(r'^editarFactura/(?P<pk>.+)/(?P<rfc>.+)$', views.editar_Factura, name='editarFactura'),
	url(r'^consultaFactura/(?P<pk>.+)/(?P<rfc>.+)$', views.consultar_Factura, name='consultaFactura'),
	url(r'^registroFactura/(.+)$', views.registrar_Factura, name='registroFactura'),
]

ConsultoriaBalofi/registration/urls.py
from django.conf.urls import url
from registration import views

app_name = "registration"
urlpatterns = [
	# sessions
	url(r'^$', views.LoginView.as_view(), name='login'),
	url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
	# register
	url(r'^register/$', views.RegisterView.as_view(), name='register'),
	url(r'^register/success/$',views.RegisterSuccessView.as_view(), name='register-success'),
]

ConsultoriaBalofi/balofi/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Clientes(models.Model):
	rfc = models.CharField(max_length=13, primary_key=True)
	password = models.CharField(max_length=20)
	nombre = models.CharField(max_length=30)
	aPaterno = models.CharField(max_length=50)
	aMaterno = models.CharField(max_length=50)
	direccion = models.CharField(max_length=100)
	telefono = models.CharField(max_length=10)
	correo = models.EmailField(max_length=50)
	razonSocial = models.CharField(max_length=50)
	giro = models.CharField(max_length=50)
	
class Productos(models.Model):
	idProducto = models.IntegerField(primary_key=True)
	nombre = models.CharField(max_length=50)
	marca = models.CharField(max_length=50)
	color = models.CharField(max_length=15)
	tamanio = models.CharField(max_length=15)
	numeroDePiezas = models.IntegerField(default=1)
	entradaOSalida = models.IntegerField(default=0)
	fechaMovimiento = models.DateField(auto_now=False,auto_now_add=False)
	caducidad = models.DateField(auto_now=False,auto_now_add=False)
	cantidad = models.IntegerField(default=1)
	cliente = models.CharField(max_length=13)
	
class Facturas(models.Model):
	idFactura = models.AutoField(primary_key=True)
	rfcEmisor = models.CharField(max_length=13)
	nombreEmisor = models.CharField(max_length=50)
	direccionEmisor = models.CharField(max_length=100)
	fecha = models.DateField(auto_now=False,auto_now_add=False)
	rfcReceptor = models.CharField(max_length=13)
	nombreReceptor = models.CharField(max_length=50)
	direccionReceptor = models.CharField(max_length=100)
	tipo = models.IntegerField(default=0)
	subtotal = models.DecimalField(max_digits=10,decimal_places=4)
	IVA = models.DecimalField(max_digits=10,decimal_places=4)
	total = models.DecimalField(max_digits=10,decimal_places=4)
	cliente = models.CharField(max_length=13)

ConsultoriaBalofi/balofi/forms.py
from django import forms
from .models import Clientes, Productos, Facturas


class FormCliente(forms.ModelForm):
	class Meta:
		model=Clientes
		fields=('rfc','password','nombre','aPaterno','aMaterno','direccion','telefono','correo','razonSocial','giro',)
		
class FormProducto(forms.ModelForm):
	class Meta:
		model=Productos
		fields=('nombre','marca','color','tamanio','numeroDePiezas','entradaOSalida','fechaMovimiento','caducidad',)
		
class FormFactura(forms.ModelForm):
	class Meta:
		model=Facturas
		fields=('rfcEmisor','nombreEmisor','direccionEmisor','fecha','rfcReceptor','nombreReceptor','direccionReceptor','tipo','subtotal','IVA','total')
		

ConsultoriaBalofi/balofi/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Clientes, Productos, Facturas
from .forms import FormCliente, FormProducto, FormFactura
from django.http import HttpResponse



# Create your views here.
def Home(request):
	clientes = Clientes.objects.all()
	return render(request, 'balofi/Home.html',{'clientes':clientes})

def editar(request, pk):
	cliente = get_object_or_404(Clientes, pk=pk)
	if request.method == "POST":
		form = FormCliente(request.POST,instance=cliente)
		if form.is_valid():
			x = form.save(commit=False)
			cliente.save()
			return redirect(Home)
	else:
		form = FormCliente(instance = cliente)
		return render(request,'balofi/editar.html',{'form':form})
	form=FormCliente(instance = cliente)
	return render(request, 'balofi/editar.html', {'form':form})
	
def consultar(request, pk):
	x = get_object_or_404(Clientes, pk=pk)
	clientes = Clientes.objects.filter(rfc=x.rfc)
	return render(request, 'balofi/consultar.html', {'clientes':clientes})

def registrar(request):
	if request.method == "POST":
		form = FormCliente(request.POST)
		if form.is_valid():
			cliente = form.save(commit=False)
			cliente.save()
			return redirect(Home)
	else:
		form=FormCliente()
	return render(request,'balofi/registrar.html',{'form':form})
	#return render(request, 'balofi/registrar.html', {})
	

def VerProductos(request, pk):
	x = get_object_or_404(Clientes, pk=pk)
	productos = Productos.objects.filter(cliente=x.rfc)
	return render(request, 'balofi/productos.html', {'productos':productos, 'clientes':x})
		
def editar_Producto(request, pk, rfc):
	producto = get_object_or_404(Productos, pk=pk)
	cliente = get_object_or_404(Clientes, rfc=rfc)
	if request.method == "POST":
		form = FormProducto(request.POST,instance=producto)
		if form.is_valid():
			x = form.save(commit=False)
			producto.save()
			return redirect(VerProductos, cliente.rfc)
	else:
		form = FormProducto(instance = producto)
		return render(request,'balofi/editarProducto.html',{'form':form, 'cliente':cliente})
	form=Formproducto(instance = producto)
	return render(request, 'balofi/editarProducto.html', {'form':form, 'cliente':cliente})
	
def consultar_Producto(request, pk, rfc):
	x = get_object_or_404(Productos, pk=pk)
	y = get_object_or_404(Clientes, rfc=rfc)
	productos = Productos.objects.filter(idProducto=x.idProducto)
	return render(request, 'balofi/consultarProducto.html', {'productos':productos, 'cliente':y})
	
def registrar_Producto(request, pk):
	x = get_object_or_404(Clientes, pk=pk)
	if request.method == "POST":
		form = FormProducto(request.POST)
		if form.is_valid():
			producto = form.save(commit=False)
			producto.cliente = x.rfc
			producto.save()
			return redirect(VerProductos, x.rfc)
	else:
		form=FormProducto()
	return render(request,'balofi/registrarProducto.html',{'form':form, 'cliente':x})
	

def VerFacturas(request, pk):
	x = get_object_or_404(Clientes, pk=pk)
	facturas = Facturas.objects.filter(cliente=x.rfc)
	return render(request, 'balofi/facturas.html', {'facturas':facturas, 'clientes':x})
	
def editar_Factura(request, pk, rfc):
	factura = get_object_or_404(Facturas, pk=pk)
	cliente = get_object_or_404(Clientes, rfc=rfc)
	if request.method == "POST":
		form = FormFactura(request.POST,instance=factura)
		if form.is_valid():
			x = form.save(commit=False)
			factura.save()
			return redirect(VerFacturas, cliente.rfc)
	else:
		form = FormFactura(instance = factura)
		return render(request,'balofi/editarFactura.html',{'form':form, 'cliente':cliente})
	form=FormFactura(instance = factura)
	return render(request, 'balofi/editarFactura.html', {'form':form, 'cliente':cliente})
	
def consultar_Factura(request, pk, rfc):
	x = get_object_or_404(Facturas, pk=pk)
	y = get_object_or_404(Clientes, rfc=rfc)
	facturas = Facturas.objects.filter(idFactura=x.idFactura)
	return render(request, 'balofi/consultarFactura.html', {'facturas':facturas, 'cliente':y})
	
def registrar_Factura(request, pk):
	x = get_object_or_404(Clientes, pk=pk)
	if request.method == "POST":
		form = FormFactura(request.POST)
		if form.is_valid():
			factura = form.save(commit=False)
			factura.cliente = x.rfc
			factura.save()
			return redirect(VerFacturas, x.rfc)
	else:
		form=FormFactura()
	return render(request,'balofi/registrarFactura.html',{'form':form, 'cliente':x})

ConsultoriaBalofi/balofi/templates/balofi/Home.html
{% load i18n staticfiles %}
<html>
<head>
<title>Balofi</title>
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/bootstrap-theme.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/base.css' %}" />
</head>

<body>
<a href={% url 'registration:login' %}>Cerrar sesi&oacute;n</a>
 <div class="container">
  <h2 class="form-signin-heading">Balofi</h2>
 </div>
    <div class="container">
    <table>
	 <tr><td>Cliente</td><td>RFC</td><td>Enlaces</td></tr>
 {% for cliente in clientes %}
	 <tr><td>{{cliente.nombre}} {{cliente.aPaterno}} {{cliente.aMaterno}}</td><td>{{cliente.rfc}}</td><td><a href={% url 'cliente' cliente.pk %}><button class="btn btn-lg btn-primary btn-block" type="submit">Editar</button></a></td><td><a href={% url 'consulta' cliente.rfc %}><button  class="btn btn-lg btn-primary btn-block" type="submit">Consultar</button></a></td></tr>
 {% endfor %}
 	<tr><td>Registrar nuevo cliente:</td><td><a href={% url 'registro' %}>Click aqu&iacute;</a></td></tr>
	<tr><td></td></tr>
  	</table>
   </div>
</body>
</html>

ConsultoriaBalofi/balofi/templates/balofi/consultar.html
{% load i18n staticfiles %}
<html>
<head>
<title>Balofi</title>
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/bootstrap-theme.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/base.css' %}" />
</head>

<body>
 <a href={% url 'registration:login' %}>Cerrar sesi&oacute;n</a>
 <div class="container">
  <h2 class="form-signin-heading">Balofi</h2>
 </div>
    <div class="container">
	 {% for cliente in clientes %}
    <table>
	 <tr><td>RFC:</td><td>{{cliente.rfc}}</td></tr>
	 <tr><td>Password:</td><td>{{cliente.password}}</td></tr>
	 <tr><td>Nombre:</td><td>{{cliente.nombre}}</td></tr>
	 <tr><td>Apellido Paterno:</td><td>{{cliente.aPaterno}}</td></tr>
	 <tr><td>Apellido Materno:</td><td>{{cliente.aMaterno}}</td></tr>
	 <tr><td>Direcci&oacute;n:</td><td>{{cliente.direccion}}</td></tr>
	 <tr><td>Tel&eacute;fono:</td><td>{{cliente.telefono}}</td></tr>
	 <tr><td>Correo:</td><td>{{cliente.correo}}</td></tr>
	 <tr><td>Raz&oacute;n Social:</td><td>{{cliente.razonSocial}}</td></tr>
	 <tr><td>Giro:</td><td>{{cliente.giro}}</td></tr>
 
  <tr><td>Productos:</td><td><a href={% url 'productos' cliente.pk %}><button  class="btn btn-lg btn-primary btn-block" type="submit">Inventario</button></a></td></tr>
  <tr><td>Facturas:</td><td><a href={% url 'facturas' cliente.pk %}><button class="btn btn-lg btn-primary btn-block" type="submit">Facturas</button></a></td></tr>
  	
   {% endfor %}
  	<tr><td><a href={% url 'Home' %}><button  class="btn btn-lg btn-primary btn-block" type="submit">Regresar</button></a></td></tr>
	</table>
   </div>
</body>
</html>

ConsultoriaBalofi/balofi/templates/balofi/consultarFactura.html
{% load i18n staticfiles %}
<html>
<head>
<title>Balofi</title>
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/bootstrap-theme.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/base.css' %}" />
</head>

<body>
  <a href={% url 'registration:login' %}>Cerrar sesi&oacute;n</a>
 <div class="container">
  <h2 class="form-signin-heading">Balofi</h2>
 </div>
    <div class="container">
	 {% for factura in facturas %}
    <table>
	 <tr><td>Id:</td><td>{{factura.idFactura}}</td></tr>
	 <tr><td>RFC del Emisor:</td><td>{{factura.rfcEmisor}}</td></tr>
	 <tr><td>Nombre del Emisor:</td><td>{{factura.nombreEmisor}}</td></tr>
	 <tr><td>Direcci&oacute;n del Emisor:</td><td>{{factura.direccionEmisor}}</td></tr>
	 <tr><td>Fecha de emisi$oacute;n:</td><td>{{factura.fecha}}</td></tr>
	 <tr><td>RFC del Receptor:</td><td>{{factura.rfcReceptor}}</td></tr>
	 <tr><td>Nombre del Receptor:</td><td>{{factura.nombreReceptor}}</td></tr>
	 <tr><td>Direcci&oacute;n del Receptor:</td><td>{{factura.direccionReceptor}}</td></tr>
	 <tr><td>Tipo de movimiento:</td>
	 {% if factura.tipo == 0 %}
	  <td>Egreso</td></tr>
	 {% else %}
	  <td>Ingreso</td></tr>
	 {% endif %}
	 <tr><td>Subtotal:</td><td>{{factura.subtotal}}</td></tr>
	 <tr><td>IVA:</td><td>{{factura.IVA}}</td></tr>
	 <tr><td>Total:</td><td>{{factura.total}}</td></tr>
	 <tr><td>Cliente:</td><td>{{factura.cliente}}</td></tr>
 {% endfor %}
  	<tr><td><a href={% url 'facturas' cliente.pk %}><button class="btn btn-lg btn-primary btn-block" type="submit">Regresar</button></a></td></tr>
   </table>
   </div>
</body>
</html>

ConsultoriaBalofi/balofi/templates/balofi/consultarProducto.html
{% load i18n staticfiles %}
<html>
<head>
<title>Balofi</title>
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/bootstrap-theme.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/base.css' %}" />
</head>

<body>
  <a href={% url 'registration:login' %}>Cerrar sesi&oacute;n</a>
 <div class="container">
  <h2 class="form-signin-heading">Balofi</h2>
 </div>
    <div class="container">
	 {% for producto in productos %}
    <table>
	 <tr><td>Id:</td><td>{{producto.idProducto}}</td></tr>
	 <tr><td>Nombre:</td><td>{{producto.nombre}}</td></tr>
	 <tr><td>Marca:</td><td>{{producto.marca}}</td></tr>
	 <tr><td>Color:</td><td>{{producto.color}}</td></tr>
	 <tr><td>Tama&ntilde;o:</td><td>{{producto.tamanio}}</td></tr>
	 <tr><td>N&uacute;mero de Piezas:</td><td>{{producto.numeroDePiezas}}</td></tr>
	 <tr><td>Caducidad:</td><td>{{producto.caducidad}}</td></tr>
	 <tr><td>Entrada o Salida:</td>
	 {% if producto.entradaOSalida == 0 %}
	  <td>Entrada</td>
	 {% else %}
	  <td>Salida</td>
	 {% endif %}
	 </tr>
	 <tr><td>Fecha del Movimiento:</td><td>{{producto.fechaMovimiento}}</td></tr>
	 <tr><td>Cliente:</td><td>{{producto.cliente}}</td></tr>
 {% endfor %}
  	<tr><td><a href={% url 'productos' cliente.pk %}><button class="btn btn-lg btn-primary btn-block" type="submit">Regresar</button></a></td></tr>
	</table>
   </div>
</body>
</html>

ConsultoriaBalofi/balofi/templates/balofi/editar.html
{% load i18n staticfiles %}
<html>
<head>
<title>Balofi</title>
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/bootstrap-theme.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/base.css' %}" />
</head>

<body>
  <a href={% url 'registration:login' %}>Cerrar sesi&oacute;n</a>
 <div class="container">
  <h2 class="form-signin-heading">Balofi</h2>
 </div>
 <div class="container">
{% block content %}
<form method="POST" class="clientes-form">{% csrf_token %}
{{form.as_p}}
<table>
<tr><td><button type='submit' class="btn btn-lg btn-primary btn-block">Guardar</button></td><td></td></tr>
</form>
{% endblock %}
 </div>
 <div clas="container">
  <tr><td><a href={% url 'Home' %}><button class="btn btn-lg btn-primary btn-block" type="submit">Regresar</button></a></td><td></td></tr>
  </div>
  </table>
</body>
</html>

ConsultoriaBalofi/balofi/templates/balofi/editarFactura.html
{% load i18n staticfiles %}
<html>
<head>
<title>Balofi</title>
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/bootstrap-theme.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/base.css' %}" />
</head>

<body>
  <a href={% url 'registration:login' %}>Cerrar sesi&oacute;n</a>
 <div class="container">
  <h2 class="form-signin-heading">Balofi</h2>
 </div>
 <div class="container">
{% block content %}
<form method="POST" class="productos-form">{% csrf_token %}
{{form.as_p}}
<table>
<tr><td><button type='submit' class="btn btn-lg btn-primary btn-block">Guardar</button></td><td></td></tr>
</form>
{% endblock %}
</div>
 <div clas="container">
  <tr><td><a href={% url 'facturas' cliente.pk %}><button class="btn btn-lg btn-primary btn-block" type="submit">Regresar</button></a></td><td></td></tr>
  </div>
  </table>
</body>
</html>

ConsultoriaBalofi/balofi/templates/balofi/editarProducto.html
{% load i18n staticfiles %}
<html>
<head>
<title>Balofi</title>
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/bootstrap-theme.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/base.css' %}" />
</head>

<body>
  <a href={% url 'registration:login' %}>Cerrar sesi&oacute;n</a>
 <div class="container">
  <h2 class="form-signin-heading">Balofi</h2>
 </div>
 <div class="container">
{% block content %}
<form method="POST" class="productos-form">{% csrf_token %}
{{form.as_p}}
<table>
<tr><td><button type='submit' class="btn btn-lg btn-primary btn-block">Guardar</button></td><td></td></tr>
</form>
{% endblock %}
</div>
 <div clas="container">
  <tr><td><a href={% url 'productos' cliente.pk %}><button class="btn btn-lg btn-primary btn-block" type="submit">Regresar</button></a></td><td></td></tr>
  </div>
  </table>
</body>
</html>

ConsultoriaBalofi/balofi/templates/balofi/facturas.html
{% load i18n staticfiles %}
<html>
<head>
<title>Balofi</title>
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/bootstrap-theme.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/base.css' %}" />
</head>

<body>
  <a href={% url 'registration:login' %}>Cerrar sesi&oacute;n</a>
 <div class="container">
  <h2 class="form-signin-heading">Balofi</h2>
 </div>
 <div class="container">
    <table>
	 <tr><td>Emisor</td><td>Receptor</td><td>Fecha</td><td>Subtotal</td><td>IVA</td><td>Total</td><td>Enlaces</td></tr>
 {% for factura in facturas %}
	 <tr><td>{{factura.rfcEmisor}}</td>
	 <td>{{factura.rfcReceptor}}</td>
	 <td>{{factura.fecha}}</td>
	 <td>{{factura.subtotal}}</td>
	 <td>{{factura.IVA}}</td>
	 <td>{{factura.total}}</td>
	 <td><a href={% url 'editarFactura' pk=factura.pk rfc=clientes.pk %}><button class="btn btn-lg btn-primary btn-block" type="submit">Editar</button></a></td>
	  <td><a href={% url 'consultaFactura' pk=factura.pk rfc=clientes.pk %}><button class="btn btn-lg btn-primary btn-block" type="submit">Consultar</button></a></td></tr>
 {% endfor %}
 	<tr><td>Registrar nueva factura:</td><td><a href={% url 'registroFactura' clientes.pk %}>Click aqu&iacute;</a></td></tr>
  	
   
   <tr><td><a href={% url 'consulta' clientes.pk %}><button class="btn btn-lg btn-primary btn-block" type="submit">Regresar</button></a></td><td></td></tr>
   </table>
   </div>
</body>
</html>

ConsultoriaBalofi/balofi/templates/balofi/productos.html
{% load i18n staticfiles %}
<html>
<head>
<title>Balofi</title>
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/bootstrap-theme.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/base.css' %}" />
</head>

<body>
  <a href={% url 'registration:login' %}>Cerrar sesi&oacute;n</a>
 <div class="container">
  <h2 class="form-signin-heading">Balofi</h2>
 </div>
 <div class="container">
    <table>
	 <tr><td>Producto / Marca</td><td>Entrada/Salida</td><td>Fecha</td><td>Enlaces</td></tr>
 {% for producto in productos %}
	 <tr><td>{{producto.nombre}} / {{producto.marca}}</td>
	 {% if producto.entradaOSalida == 0 %}
	   <td>Entrada</td>
	 {% else %}
	 	<td>Salida</td>
	 {% endif %}
	  <td><a href={% url 'editarProducto' pk=producto.pk rfc=clientes.pk %}><button class="btn btn-lg btn-primary btn-block" type="submit">Editar</button></a></td>
	  <td><a href={% url 'consultaProducto' pk=producto.pk rfc=clientes.pk %}><button class="btn btn-lg btn-primary btn-block" type="submit">Consultar</button></a></td></tr>
 {% endfor %}
 	<tr><td>Registrar nuevo producto:</td><td><a href={% url 'registroProducto' clientes.pk %}>Click aqu&iacute;</a></td></tr>
   
   <tr><td><a href={% url 'consulta' clientes.pk %}><button class="btn btn-lg btn-primary btn-block" type="submit">Regresar</button></a></td></tr>
   </table>
   </div>
</body>
</html>

ConsultoriaBalofi/balofi/templates/balofi/registrar.html
{% load i18n staticfiles %}
<html>
<head>
<title>Balofi</title>
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/bootstrap-theme.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/base.css' %}" />
</head>

<body>
  <a href={% url 'registration:login' %}>Cerrar sesi&oacute;n</a>
 <div class="container">
  <h2 class="form-signin-heading">Balofi</h2>
 </div>
 <div class="container">
{% block content %}
<form method="POST" class="clientes-form">{% csrf_token %}
{{form.as_p}}
<table>
<tr><td><button type='submit' class="btn btn-lg btn-primary btn-block">Guardar</button></td><td></td></tr>
</table>
</form>
{% endblock %}
</div>
 <div clas="container">
 <table>
  <tr><td><a href={% url 'Home' %}><button class="btn btn-lg btn-primary btn-block">Regresar</button></a></td><td></td></tr>
  </div>
  </table>
</body>
</html>

ConsultoriaBalofi/balofi/templates/balofi/registrarFactura.html
{% load i18n staticfiles %}
<html>
<head>
<title>Balofi</title>
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/bootstrap-theme.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/base.css' %}" />
</head>

<body>
  <a href={% url 'registration:login' %}>Cerrar sesi&oacute;n</a>
 <div class="container">
  <h2 class="form-signin-heading">Balofi</h2>
 </div>
 <div class="container">
{% block content %}
<form method="POST" class="productos-form">{% csrf_token %}
{{form.as_p}}
<table>
<tr><td><button type='submit' class="btn btn-lg btn-primary btn-block">Guardar</button></td><td></td></tr>
</table>
</form>
{% endblock %}
</div>
 <div clas="container">
 <table>
  <tr><td><a href={% url 'facturas' cliente.pk %}><button class="btn btn-lg btn-primary btn-block" type="submit">Regresar</button></a></td><td></td></tr>
  </div>
  </table>
</body>
</html>

ConsultoriaBalofi/balofi/templates/balofi/registrarProducto.html
{% load i18n staticfiles %}
<html>
<head>
<title>Balofi</title>
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/bootstrap-theme.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'balofi/css/base.css' %}" />
</head>

<body>
  <a href={% url 'registration:login' %}>Cerrar sesi&oacute;n</a>
 <div class="container">
  <h2 class="form-signin-heading">Balofi</h2>
 </div>
 <div class="container">
{% block content %}
<form method="POST" class="productos-form">{% csrf_token %}
{{form.as_p}}
<table>
<tr><td><button type='submit' class="btn btn-lg btn-primary btn-block">Guardar</button></td><td></td></tr>
</table>
</form>
{% endblock %}
</div>
 <div clas="container">
 <table>
 <tr><td><a href={% url 'productos' cliente.pk %}><button class="btn btn-lg btn-primary btn-block" type="submit">Regresar</button></a></td><td></td></tr>
  </div>
  </table>
</body>
</html>